Transfer to the new repo
LightnessOfBeing/Java1 pull request #2
Opened 2017-10-18 02:42 UTC by LightnessOfBeing

2017-10-22 07:55 UTC, yurii-litvinov requested changes
Бинарники в гит не надо выкладывать. Могу порекомендовать вот это: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore плюс вот это: https://github.com/github/gitignore/blob/master/Gradle.gitignore плюс вот это: https://github.com/github/gitignore/blob/master/Java.gitignore

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/Main.java
> +    public static void main(String[] args){
Перед "{" нужен пробел, здесь и ниже

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/Main.java
> +    }
А перед "}" пустая строчка обычно не ставится

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +    private final int n;
Размер массива можно не хранить, массив сам его знает

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +    SpiralMatrix(int n, int[][] array){
Класс паблик, а конструктор имеет пакетную видимость, так и задумывалось?

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +            System.arraycopy(array[i], 0, matrix[i], 0, n);
Надо бы ещё проверять, что нам передали, и если что, адекватно ругаться

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +    void sortMatrixByRows(){
Эта штука тоже, наверное, должна быть public, она упоминается в условии задачи

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +    void transposeMatrix(){
Пакетная видимость по какой-то причине, или просто видимость не указана?

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +    public int[][] getMatrix(){
О, паблик-метод без комментария :)

2017-10-22 07:55 UTC, yurii-litvinov commented on gradleSpiralMatrix/src/test/java/ru/spbau/mit/vishnyakov/SpiralMatrixTest.java
> +
Ещё надо бы плохие случаи проверить, когда передаётся заведомо неправильная матрица (например, `new int[][]{{1, 2, 3}, {4, 5}, {6}}` или null), программа должна адекватно реагировать на такие ситуации

2017-10-22 08:12 UTC, LightnessOfBeing commented on gradleSpiralMatrix/src/main/java/ru/spbau/mit/vishnyakov/SpiralMatrix.java
> +    public int[][] getMatrix(){
Нам на одной из смерженных практик Тимофей говорил, что у геттеров и сеттеров можно не писать комментарии.

2017-10-31 14:01 UTC, yurii-litvinov requested changes
Надо ещё лишние файлы поудалять, даже без .gitignore, вручную просто. В остальном теперь всё ок

2017-10-31 14:01 UTC, yurii-litvinov commented on gradleSpiralMatrix/build/reports/tests/test/classes/ru.spbau.mit.vishnyakov.SpiralMatrixTest.html
> +<!DOCTYPE html>
Это тоже надо удалить, это что-то сгенерённое

2017-10-31 14:01 UTC, yurii-litvinov commented on gradleSpiralMatrix/build/reports/tests/test/css/base-style.css
> +
И это

2017-12-04 03:59 UTC, yurii-litvinov requested changes
Не-а, надо вообще всю папку build грохнуть

2017-12-07 16:53 UTC, yurii-litvinov approved these changes
Ага, теперь всё так, зачтена

2018-02-13 17:56 UTC, merged